# Generated by Django 5.2 on 2025-05-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placelog',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
