# Generated by Django 5.2 on 2025-05-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_usercategory_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='color',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
