# Generated by Django 5.2 on 2025-05-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_usercategory_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeinfo',
            unique_together={('name', 'address', 'language')},
        ),
    ]
