# Generated by Django 5.2 on 2025-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_placeinfochangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='reference_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
