# Generated by Django 5.2 on 2025-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_placeinfo_reference_urls'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeinfo',
            unique_together={('name', 'language')},
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
